<?php
/**
 * @file
 * os2web_news_page.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function os2web_news_page_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'field_bundle_settings_node__os2web_base_news';
  $strongarm->value = array(
    'view_modes' => array(
      'teaser' => array(
        'custom_settings' => TRUE,
      ),
      'related_block' => array(
        'custom_settings' => TRUE,
      ),
      'full' => array(
        'custom_settings' => FALSE,
      ),
      'rss' => array(
        'custom_settings' => FALSE,
      ),
      'search_index' => array(
        'custom_settings' => FALSE,
      ),
      'search_result' => array(
        'custom_settings' => FALSE,
      ),
      'print' => array(
        'custom_settings' => FALSE,
      ),
      'token' => array(
        'custom_settings' => FALSE,
      ),
      'os2web_meetings_meeting_detail_view' => array(
        'custom_settings' => FALSE,
      ),
      'revision' => array(
        'custom_settings' => FALSE,
      ),
      'spotboks' => array(
        'custom_settings' => TRUE,
      ),
      'spotbox' => array(
        'custom_settings' => TRUE,
      ),
      'diff_standard' => array(
        'custom_settings' => FALSE,
      ),
      'list' => array(
        'custom_settings' => TRUE,
      ),
      'list_advanced' => array(
        'custom_settings' => TRUE,
      ),
      'list_simple' => array(
        'custom_settings' => TRUE,
      ),
    ),
    'extra_fields' => array(
      'display' => array(
        'language' => array(
          'default' => array(
            'weight' => '0',
            'visible' => FALSE,
          ),
          'list_advanced' => array(
            'weight' => '0',
            'visible' => FALSE,
          ),
          'list_simple' => array(
            'weight' => '0',
            'visible' => FALSE,
          ),
          'list' => array(
            'weight' => '0',
            'visible' => FALSE,
          ),
        ),
      ),
      'form' => array(
        'title' => array(
          'weight' => '1',
        ),
        'path' => array(
          'weight' => '3',
        ),
        'workbench_access' => array(
          'weight' => '0',
        ),
        'metatags' => array(
          'weight' => '2',
        ),
        'redirect' => array(
          'weight' => '5',
        ),
      ),
    ),
  );
  $export['field_bundle_settings_node__os2web_base_news'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'language_content_type_os2web_base_news';
  $strongarm->value = '0';
  $export['language_content_type_os2web_base_news'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'menu_options_os2web_base_news';
  $strongarm->value = array();
  $export['menu_options_os2web_base_news'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'menu_parent_os2web_base_news';
  $strongarm->value = 'os2web-menu-contentmenu:0';
  $export['menu_parent_os2web_base_news'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'metatag_enable_node__os2web_base_news';
  $strongarm->value = TRUE;
  $export['metatag_enable_node__os2web_base_news'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'metatag_enable_taxonomy_term__os2web_news_page_newstypes';
  $strongarm->value = TRUE;
  $export['metatag_enable_taxonomy_term__os2web_news_page_newstypes'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_options_os2web_base_news';
  $strongarm->value = array(
    0 => 'status',
    1 => 'revision',
  );
  $export['node_options_os2web_base_news'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_preview_os2web_base_news';
  $strongarm->value = '1';
  $export['node_preview_os2web_base_news'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'node_submitted_os2web_base_news';
  $strongarm->value = 0;
  $export['node_submitted_os2web_base_news'] = $strongarm;

  return $export;
}
